### ISSUE TITLE
mirrord not loaded in IntelliJ/Java project on Google Cloud Workstation

### ISSUE THREAD

**Issue by thorstenhirsch** [metalbear-co/mirrord#2007]
### Bug Description

While the mirrord plugin in IntelliJ seems to work fine, there's no sign of mirrord when running the actual Java code. There's also no popup asking me for the target k8s pod. Specifying the target in the mirrord settings has no effect. Also, providing `RUST_LOG=warn,mirrord=trace` as an environment variable has no effect.

The environment is probably to blame. I'm running a remote IntelliJ session on a Google Cloud Workstation (Linux VM) via IntelliJ Gateway, so IntelliJ is split:

- an IntelliJ fronted running on a Windows 10 machine
- a backend runing on a Linux VM

A few things seem weird:

- the mirrord plugin works fine, but whenever I start an IntelliJ session it downloads the mirrord binary again (maybe it's not persisted)
- the mirrord icon is there and it allows me to see & edit the mirrord settings, but they are persistent only as long as the IntelliJ session runs; new session means `mirrord.json` is reset and contains the default settings only

Please take a look at the attached screenshot (coming soon...)! I think `mirrord.json` is being created on the Win10 machine instead of the Linux VM backend machine. Also I guess the mirrod binary is being stored on the Win10 machine - at least I couldn't find it on the Linux VM backend machine. There's also no `mirrord.json` on the Linux VM backend machine.

### Steps to Reproduce

1. Install mirrord plugin in IntelliJ
2. Enable plugin (popup "mirrod enabled" appears, popup "downloaded mirrord binary version 3.72.0" appears)
3. Start debug session (runs as if mirrord is not enabled at all)

### Your operating system and version

Win10 frontend, Linux backend

### Local process

java

### Local process version

17

**Comment by thorstenhirsch** [comment]
![mirrord-json-on-local-win10-machine](https://github.com/metalbear-co/mirrord/assets/619741/433016cd-b47b-4612-83a7-f0ae26f221db)

**Comment by lanbabaJZS** [comment]
I'm having the same issue,my environment :
an IntelliJ fronted running on a Windows 11 machine
a backend runing on a WSL

**Comment by infiniteregrets** [comment]
hi @thorstenhirsch is the plugin installed on the host or on the client?

<img width="227" alt="Screenshot 2023-11-12 at 8 50 07 PM" src="https://github.com/metalbear-co/mirrord/assets/65443164/3735d3db-f54b-42a4-a59f-c5edc6d6cb41">

**Comment by infiniteregrets** [comment]
> I'm having the same issue,my environment : an IntelliJ fronted running on a Windows 11 machine a backend runing on a WSL

hi, @lanbabaJZS I have opened https://github.com/metalbear-co/mirrord-intellij/pull/194 that should fix the problem you are facing! I will drop an update for you as soon that is released!

**Comment by thorstenhirsch** [comment]
Hi @infiniteregrets, the bug (as described so far) occurs when the plugin is installed **on the client only**.

Obviously, now I've installed it on the host as well. But mirrord still doesn't work. Here's the error message when the plugin is installed **on the client and on the host**:
![mirrord-plugin-error](https://github.com/metalbear-co/mirrord/assets/619741/791429d4-014a-4ebf-8a87-44615d4e6ac9)

**Comment by infiniteregrets** [comment]
> Hi @infiniteregrets, the bug (as described so far) occurs when the plugin is installed **on the client only**.
> 
> Obviously, now I've installed it on the host as well. But mirrord still doesn't work. Here's the error message when the plugin is installed **on the client and on the host**: ![mirrord-plugin-error](https://user-images.githubusercontent.com/619741/282504786-791429d4-014a-4ebf-8a87-44615d4e6ac9.PNG)

That looks quite odd, I don't think its related to the plugin. Do you mind restarting your connection?

**Comment by thorstenhirsch** [comment]
Right... I restarted everything and also made sure that `kubectl` works on the host by running `gcloud auth login` in IntelliJ's terminal, which opens a session on the host. However, mirrord still doesn't work.

- When I enable mirrord IntelliJ is hanging at "starting application" (no matter if debug or normal mode) and then running on a timeout. Then I need to restart IntelliJ as no operation works anymore, not even building the code.
- When mirrord is disabled IntelliJ can successfully start the Java application locally on the client, but only once. When stopping the application I also need to restart IntelliJ completely as it hangs the same way as above.

And still I couldn't find any traces of mirrord's json config on the host. I think it's only available on the client, which is the wrong side since it contains (or can contain) the necessary information for the host to connect to k8s with kubectl.

The whole IntelliJ Gateway architecture seems broken to me. As we can see: it's not just forwarding the UI from the host. Instead there's a client and a host. Why am I able to choose on which side to install plugins? It's an utter mess to find out what parts of a plugin run on which side and how they communicate with each other (my guess: not at all).

**Comment by infiniteregrets** [comment]
> Right... I restarted everything and also made sure that `kubectl` works on the host by running `gcloud auth login` in IntelliJ's terminal, which opens a session on the host. However, mirrord still doesn't work.
> 
> * When I enable mirrord IntelliJ is hanging at "starting application" (no matter if debug or normal mode) and then running on a timeout. Then I need to restart IntelliJ as no operation works anymore, not even building the code.
> * When mirrord is disabled IntelliJ can successfully start the Java application locally on the client, but only once. When stopping the application I also need to restart IntelliJ completely as it hangs the same way as above.
> 
> And still I couldn't find any traces of mirrord's json config on the host. I think it's only available on the client, which is the wrong side since it contains (or can contain) the necessary information for the host to connect to k8s with kubectl.
> 
> The whole IntelliJ Gateway architecture seems broken to me. As we can see: it's not just forwarding the UI from the host. Instead there's a client and a host. Why am I able to choose on which side to install plugins? It's an utter mess to find out what parts of a plugin run on which side and how they communicate with each other (my guess: not at all).

Thanks for trying @thorstenhirsch, unfortunately I have not been able to get the extension to even properly load in the IDE with gateway if installed on host, however I do think it's possible to run it, but on the client it might not be. I will give this another try and possibly make some changes to our setup. I will keep you posted if I end up making progress on it. Thanks for your patience!

**Comment by eyalb181** [comment]
Possibly related: https://discord.com/channels/933706914808889356/950020257156833340/1280056160535449610

**Comment by DmitryDodzin** [comment]
Hi, I've tested Google Cloud workstations + IntelliJ IDEA 2024.2.1 with mirrord plugin installed (only on the "host" and with both host and client having the plugin didn't seem to change anything) it seems to to work as expected after I copied over my `.kube` config and `kubectl get po` works in the intellij terminal.

I did run into issues when I set a project directory to a path where IntelliJ could not create the `.idea` folder and this did interfere with our plugin and caused a complete failure to run.

Can I be missing something?
